export const defaultSEOData = {
    seo_tags_map: {
      "home": {
        "page_id": "home",
        "page_path": "/",
        "page_name": "Home Page",
        "page_title": "EVALL - Smart Electric Commercial Vehicles for India | Last-Mile EVs",
        "meta_description": "EVALL designs smart electric commercial vehicles for efficient last-mile delivery in India. Explore our range, vehicle intelligence, and sustainable solutions.",
        "meta_keywords": "EVALL, electric commercial vehicles, last-mile EV, smart SCV, sustainable transport, India EV manufacturer",
        "canonical_url": "https://www.evall.co.in/",
        "robots_meta": "index, follow",
        "og_title": "EVALL - Smart Electric Commercial Vehicles for India",
        "og_description": "Revolutionizing last-mile delivery with smart electric commercial vehicles. Discover EVALL's connected, efficient, and sustainable SCVs.",
        "og_type": "website",
        "og_url": "https://www.evall.co.in/",
        "og_image_url": "https://www.evall.co.in/images/og-evall.png",
        "og_image_alt": "EVALL smart electric commercial vehicles",
        "twitter_card": "summary_large_image",
        "twitter_title": "EVALL - Electric Commercial Vehicles",
        "twitter_description": "India's leading electric SCV manufacturer for sustainable last-mile delivery.",
        "twitter_image_url": "https://www.evall.co.in/images/og-evall.png",
        "schema": ""
      },
      "company-overview": {
        "page_id": "company-overview",
        "page_path": "/what-drives-us/company-overview",
        "page_name": "Company Overview",
        "page_title": "About EVALL - Leading Electric Vehicle Manufacturer | Company Overview",
        "meta_description": "Learn about EVALL — India’s innovative electric commercial vehicle manufacturer. Our mission, vision, and commitment to sustainable last-mile transportation.",
        "meta_keywords": "EVALL company, about EVALL, electric vehicle manufacturer India, EV company overview, sustainable mobility mission",
        "canonical_url": "https://www.evall.co.in/what-drives-us/company-overview",
        "robots_meta": "index, follow",
        "og_title": "About EVALL - Company Overview",
        "og_description": "Leading the electric vehicle revolution in India with innovative commercial vehicles for sustainable last-mile delivery.",
        "og_type": "website",
        "og_url": "https://www.evall.co.in/what-drives-us/company-overview",
        "og_image_url": "https://www.evall.co.in/images/og-evall.png",
        "og_image_alt": "EVALL company overview",
        "twitter_card": "summary_large_image",
        "twitter_title": "About EVALL - Company Overview",
        "twitter_description": "Innovative electric vehicle manufacturer transforming commercial transportation in India.",
        "twitter_image_url": "https://www.evall.co.in/images/og-evall.png",
        "schema": ""
      },
      "careers-culture": {
        "page_id": "careers-culture",
        "page_path": "/what-drives-us/careers",
        "page_name": "Careers & Culture",
        "page_title": "Careers at EVALL - Join the Electric Mobility Team | Culture & Openings",
        "meta_description": "Join EVALL — build the future of electric commercial vehicles. See our culture, employee benefits, and current job openings across engineering, sales, and operations.",
        "meta_keywords": "EVALL careers, jobs at EVALL, EV startup jobs, company culture, electric vehicle careers, work with EVALL",
        "canonical_url": "https://www.evall.co.in/what-drives-us/careers",
        "robots_meta": "index, follow",
        "og_title": "Careers at EVALL - Culture & Openings",
        "og_description": "Work with EVALL to accelerate sustainable mobility. Explore roles in engineering, product, sales, and operations.",
        "og_type": "website",
        "og_url": "https://www.evall.co.in/what-drives-us/careers",
        "og_image_url": "https://www.evall.co.in/images/og-evall.png",
        "og_image_alt": "Careers at EVALL",
        "twitter_card": "summary_large_image",
        "twitter_title": "Careers at EVALL",
        "twitter_description": "Explore job openings and our company culture at EVALL.",
        "twitter_image_url": "https://www.evall.co.in/images/og-evall.png",
        "schema": ""
      },
      "customer-stories": {
        "page_id": "customer-stories",
        "page_path": "/what-drives-us/customer-stories",
        "page_name": "Customer Stories",
        "page_title": "Customer Stories & Case Studies - EVALL Commercial EVs in Action",
        "meta_description": "Explore customer stories and case studies showing how EVALL vehicles cut operating costs and improve delivery efficiency for fleets and businesses.",
        "meta_keywords": "EVALL customer stories, case studies, fleet electrification results, commercial EV ROI, last-mile success stories",
        "canonical_url": "https://www.evall.co.in/what-drives-us/customer-stories",
        "robots_meta": "index, follow",
        "og_title": "Customer Stories - EVALL Case Studies",
        "og_description": "Real-world results from fleets using EVALL electric commercial vehicles — savings, uptime, and sustainability outcomes.",
        "og_type": "website",
        "og_url": "https://www.evall.co.in/what-drives-us/customer-stories",
        "og_image_url": "https://www.evall.co.in/images/og-evall.png",
        "og_image_alt": "EVALL customer case studies",
        "twitter_card": "summary_large_image",
        "twitter_title": "Customer Stories - EVALL",
        "twitter_description": "See how businesses improve operations with EVALL electric commercial vehicles.",
        "twitter_image_url": "https://www.evall.co.in/images/og-evall.png",
        "schema": ""
      },
      "after-sales-service": {
        "page_id": "after-sales-service",
        "page_path": "/network/after-sales-service",
        "page_name": "After-Sales Service",
        "page_title": "After-Sales Service - EVALL Support & Maintenance",
        "meta_description": "EVALL after-sales service: maintenance plans, roadside assistance and spare parts for electric commercial vehicles to maximize uptime.",
        "meta_keywords": "after-sales service EVALL, EV maintenance, spare parts, roadside assistance, vehicle uptime",
        "canonical_url": "https://www.evall.co.in/network/after-sales-service",
        "robots_meta": "index, follow",
        "og_title": "EVALL After-Sales Service",
        "og_description": "Comprehensive support plans and genuine spare parts to keep EVALL vehicles running reliably.",
        "og_type": "website",
        "og_url": "https://www.evall.co.in/network/after-sales-service",
        "og_image_url": "https://www.evall.co.in/images/og-evall.png",
        "og_image_alt": "EVALL after-sales service",
        "twitter_card": "summary_large_image",
        "twitter_title": "After-Sales Service - EVALL",
        "twitter_description": "Maintenance, spare parts and service plans for EVALL fleets and customers.",
        "twitter_image_url": "https://www.evall.co.in/images/og-evall.png",
        "schema": ""
      },
      "charging-infrastructure": {
        "page_id": "charging-infrastructure",
        "page_path": "/network/charging-infrastructure",
        "page_name": "Charging Infrastructure & Partnerships",
        "page_title": "Charging Infrastructure & Partnerships - EVALL",
        "meta_description": "EVALL partners with charging networks and provides guidance on depot charging, fast charging options and integration for fleet operations.",
        "meta_keywords": "charging infrastructure, depot charging, EV charging partners, fast charging, fleet charging solutions",
        "canonical_url": "https://www.evall.co.in/network/charging-infrastructure",
        "robots_meta": "index, follow",
        "og_title": "Charging Infrastructure & Partnerships",
        "og_description": "Depot charging solutions, partner networks and charging strategies for efficient fleet electrification.",
        "og_type": "website",
        "og_url": "https://www.evall.co.in/network/charging-infrastructure",
        "og_image_url": "https://www.evall.co.in/images/og-evall.png",
        "og_image_alt": "EVALL charging infrastructure and partners",
        "twitter_card": "summary_large_image",
        "twitter_title": "Charging Infrastructure - EVALL",
        "twitter_description": "Depot charging, partner networks and charging strategy for fleets.",
        "twitter_image_url": "https://www.evall.co.in/images/og-evall.png",
        "schema": ""
      },
      "e-scv": {
        "page_id": "e-scv",
        "page_path": "/products/e-SCV",
        "page_name": "e-SCV Product",
        "page_title": "EVALL e-SCV - Electric Small Commercial Vehicle | Specifications & Range",
        "meta_description": "Discover EVALL e-SCV: an advanced electric small commercial vehicle for last-mile delivery with smart connectivity, long range, and low operating costs.",
        "meta_keywords": "e-SCV, electric small commercial vehicle, last-mile delivery van, EV specifications, EVALL e-SCV, commercial EV",
        "canonical_url": "https://www.evall.co.in/products/e-SCV",
        "robots_meta": "index, follow",
        "og_title": "EVALL e-SCV - Smart Electric Commercial Vehicle",
        "og_description": "Advanced e-SCV with smart connectivity, extended range, and sustainable performance for efficient last-mile delivery.",
        "og_type": "product",
        "og_url": "https://www.evall.co.in/products/e-SCV",
        "og_image_url": "https://www.evall.co.in/images/og-evall.png",
        "og_image_alt": "EVALL e-SCV electric small commercial vehicle",
        "twitter_card": "summary_large_image",
        "twitter_title": "EVALL e-SCV Electric Vehicle",
        "twitter_description": "Smart electric commercial vehicle for sustainable last-mile delivery operations.",
        "twitter_image_url": "https://www.evall.co.in/images/og-evall.png",
        "schema": ""
      },
      "vehicle-intelligence": {
        "page_id": "vehicle-intelligence",
        "page_path": "/tech-innovation/vehicle-intelligence",
        "page_name": "Vehicle Intelligence & Connectivity",
        "page_title": "Vehicle Intelligence & Connectivity - EVALL Telematics & Fleet Software",
        "meta_description": "EVALL vehicle intelligence: real-time telematics, fleet management dashboards and OTA updates to boost efficiency and uptime for commercial fleets.",
        "meta_keywords": "vehicle intelligence, telematics, fleet management, OTA updates, EV analytics, EV fleet software",
        "canonical_url": "https://www.evall.co.in/tech-innovation/vehicle-intelligence",
        "robots_meta": "index, follow",
        "og_title": "Vehicle Intelligence & Connectivity",
        "og_description": "Real-time telematics and fleet software built into EVALL vehicles for smarter operations.",
        "og_type": "website",
        "og_url": "https://www.evall.co.in/tech-innovation/vehicle-intelligence",
        "og_image_url": "https://www.evall.co.in/images/og-evall.png",
        "og_image_alt": "EVALL telematics and vehicle connectivity",
        "twitter_card": "summary_large_image",
        "twitter_title": "Vehicle Intelligence & Connectivity - EVALL",
        "twitter_description": "Telematics, remote diagnostics and fleet dashboards for EVALL customers.",
        "twitter_image_url": "https://www.evall.co.in/images/og-evall.png",
        "schema": ""
      },
      "energy-battery": {
        "page_id": "energy-battery",
        "page_path": "/tech-innovation/energy-battery",
        "page_name": "Energy Efficiency & Battery Tech",
        "page_title": "Energy & Battery Technology - EVALL EV Battery Systems",
        "meta_description": "Learn about EVALL battery technology, range optimization and energy management systems that reduce TCO and improve fleet performance.",
        "meta_keywords": "battery technology, energy efficiency, BMS, EV range optimization, battery safety, EVALL battery",
        "canonical_url": "https://www.evall.co.in/tech-innovation/energy-battery",
        "robots_meta": "index, follow",
        "og_title": "Energy Efficiency & Battery Tech",
        "og_description": "Battery tech, energy management and smart charging strategies for EVALL vehicles to maximize range and life.",
        "og_type": "website",
        "og_url": "https://www.evall.co.in/tech-innovation/energy-battery",
        "og_image_url": "https://www.evall.co.in/images/og-evall.png",
        "og_image_alt": "Battery technology and energy efficiency at EVALL",
        "twitter_card": "summary_large_image",
        "twitter_title": "Energy & Battery Technology - EVALL",
        "twitter_description": "BMS, battery safety and range optimization for EVALL electric vehicles.",
        "twitter_image_url": "https://www.evall.co.in/images/og-evall.png",
        "schema": ""
      },
      "safety-compliance": {
        "page_id": "safety-compliance",
        "page_path": "/tech-innovation/safety-compliance",
        "page_name": "Safety & Compliance Standards",
        "page_title": "Safety & Compliance - EVALL Vehicle Standards & Certifications",
        "meta_description": "EVALL's safety systems and compliance standards for commercial EVs — crashworthiness, standards certification and regulatory compliance guidance.",
        "meta_keywords": "vehicle safety, regulatory compliance, EV certifications, safety standards, EVALL safety",
        "canonical_url": "https://www.evall.co.in/tech-innovation/safety-compliance",
        "robots_meta": "index, follow",
        "og_title": "Safety & Compliance Standards",
        "og_description": "Safety features, testing and regulatory compliance details for EVALL commercial vehicles.",
        "og_type": "website",
        "og_url": "https://www.evall.co.in/tech-innovation/safety-compliance",
        "og_image_url": "https://www.evall.co.in/images/og-evall.png",
        "og_image_alt": "EVALL safety and compliance",
        "twitter_card": "summary_large_image",
        "twitter_title": "Safety & Compliance - EVALL",
        "twitter_description": "Information about safety systems and certifications for EVALL vehicles.",
        "twitter_image_url": "https://www.evall.co.in/images/og-evall.png",
        "schema": ""
      },
      "blogs": {
        "page_id": "blogs",
        "page_path": "/resources/blogs",
        "page_name": "Blog & News",
        "page_title": "EVALL Blog - Electric Vehicle News, Insights & Industry Updates",
        "meta_description": "Stay updated with the latest electric vehicle news, industry insights, and EVALL updates. Expert articles on EV technology, sustainability, and commercial transport.",
        "meta_keywords": "EV blog, electric vehicle news, EV insights, commercial EV updates, sustainable transport, EVALL blog",
        "canonical_url": "https://www.evall.co.in/resources/blogs",
        "robots_meta": "index, follow",
        "og_title": "EVALL Blog & News",
        "og_description": "Latest insights on electric vehicles, sustainable mobility, and commercial transportation innovation.",
        "og_type": "website",
        "og_url": "https://www.evall.co.in/resources/blogs",
        "og_image_url": "https://www.evall.co.in/images/og-evall.png",
        "og_image_alt": "EVALL blog and EV industry news",
        "twitter_card": "summary_large_image",
        "twitter_title": "EVALL Blog - EV News & Insights",
        "twitter_description": "Expert insights on electric vehicles and sustainable commercial transportation.",
        "twitter_image_url": "https://www.evall.co.in/images/og-evall.png",
        "schema": ""
      },
      "emi-calculator": {
        "page_id": "emi-calculator",
        "page_path": "/resources/emi-calculator",
        "page_name": "EMI Calculator",
        "page_title": "EMI Calculator - Estimate Monthly Payments for EVALL Vehicles",
        "meta_description": "Use EVALL's EMI calculator to estimate monthly loan payments for electric commercial vehicles. Quick, transparent and helpful for fleet budgeting.",
        "meta_keywords": "EMI calculator, EV loan calculator, monthly payment estimator, EV financing, fleet loan EMI",
        "canonical_url": "https://www.evall.co.in/resources/emi-calculator",
        "robots_meta": "index, follow",
        "og_title": "EMI Calculator - EVALL",
        "og_description": "Estimate monthly loan payments for EVALL vehicles with our simple EMI calculator.",
        "og_type": "website",
        "og_url": "https://www.evall.co.in/resources/emi-calculator",
        "og_image_url": "https://www.evall.co.in/images/og-evall.png",
        "og_image_alt": "EMI calculator for EVALL vehicles",
        "twitter_card": "summary_large_image",
        "twitter_title": "EMI Calculator - EVALL",
        "twitter_description": "Estimate EMI for EVALL electric commercial vehicles for easy budgeting.",
        "twitter_image_url": "https://www.evall.co.in/images/og-evall.png",
        "schema": ""
      },
      "tco-calculator": {
        "page_id": "tco-calculator",
        "page_path": "/resources/tco-calculator",
        "page_name": "TCO Calculator",
        "page_title": "TCO Calculator - Compare Total Cost of Ownership for EV Fleets",
        "meta_description": "Compare total cost of ownership (TCO) between EVALL electric vehicles and ICE alternatives with our TCO calculator — includes fuel, maintenance and incentives.",
        "meta_keywords": "TCO calculator, total cost of ownership, EV vs ICE comparison, fleet TCO, EV fleet economics",
        "canonical_url": "https://www.evall.co.in/resources/tco-calculator",
        "robots_meta": "index, follow",
        "og_title": "TCO Calculator - EVALL",
        "og_description": "Calculate and compare the total cost of ownership for EVALL vehicles and traditional vehicles.",
        "og_type": "website",
        "og_url": "https://www.evall.co.in/resources/tco-calculator",
        "og_image_url": "https://www.evall.co.in/images/og-evall.png",
        "og_image_alt": "TCO calculator for EV fleets",
        "twitter_card": "summary_large_image",
        "twitter_title": "TCO Calculator - EVALL",
        "twitter_description": "Estimate total costs for fleet electrification with EVALL's TCO tool.",
        "twitter_image_url": "https://www.evall.co.in/images/og-evall.png",
        "schema": ""
      },
      "finance-ownership": {
        "page_id": "finance-ownership",
        "page_path": "/resources/finance-ownership",
        "page_name": "Finance and Ownership",
        "page_title": "Finance & Ownership - EVALL Financing Options & Fleet Programs",
        "meta_description": "Discover EVALL financing options, lease and loan programs, government incentives, and ownership benefits for electric commercial vehicle fleets.",
        "meta_keywords": "EV financing, fleet financing, EV incentives, ownership programs, EV loan options, leasing EV",
        "canonical_url": "https://www.evall.co.in/resources/finance-ownership",
        "robots_meta": "index, follow",
        "og_title": "Finance & Ownership - EVALL",
        "og_description": "Financing, leasing and incentive guidance to help you own and operate EVALL electric commercial vehicles.",
        "og_type": "website",
        "og_url": "https://www.evall.co.in/resources/finance-ownership",
        "og_image_url": "https://www.evall.co.in/images/og-evall.png",
        "og_image_alt": "EVALL finance and ownership options",
        "twitter_card": "summary_large_image",
        "twitter_title": "Finance & Ownership - EVALL",
        "twitter_description": "Financing and ownership programs for EVALL customers and fleet operators.",
        "twitter_image_url": "https://www.evall.co.in/images/og-evall.png",
        "schema": ""
      },
      "warranty-maintenance": {
        "page_id": "warranty-maintenance",
        "page_path": "/resources/warranty-maintenance",
        "page_name": "Warranty & Maintenance",
        "page_title": "Warranty & Maintenance - EVALL Vehicle Care Plans",
        "meta_description": "Details on EVALL warranty coverage, maintenance schedules, extended warranties and service packages to protect fleet value and uptime.",
        "meta_keywords": "warranty EV, maintenance schedule, extended warranty, EV service package, EVALL warranty",
        "canonical_url": "https://www.evall.co.in/resources/warranty-maintenance",
        "robots_meta": "index, follow",
        "og_title": "Warranty & Maintenance - EVALL",
        "og_description": "Warranty terms and maintenance programs for EVALL electric vehicles to ensure reliability and lower lifecycle cost.",
        "og_type": "website",
        "og_url": "https://www.evall.co.in/resources/warranty-maintenance",
        "og_image_url": "https://www.evall.co.in/images/og-evall.png",
        "og_image_alt": "EVALL warranty and maintenance",
        "twitter_card": "summary_large_image",
        "twitter_title": "Warranty & Maintenance - EVALL",
        "twitter_description": "Read about warranty coverage and recommended maintenance for EVALL vehicles.",
        "twitter_image_url": "https://www.evall.co.in/images/og-evall.png",
        "schema": ""
      },
      "faqs": {
        "page_id": "faqs",
        "page_path": "/resources/faqs",
        "page_name": "FAQs",
        "page_title": "FAQs - EVALL Frequently Asked Questions",
        "meta_description": "Find answers to common questions about EVALL vehicles, charging, financing, maintenance and fleet operations in our FAQ section.",
        "meta_keywords": "EV FAQs, EVALL frequently asked questions, charging FAQ, financing FAQ, maintenance FAQ",
        "canonical_url": "https://www.evall.co.in/resources/faqs",
        "robots_meta": "index, follow",
        "og_title": "EVALL FAQs",
        "og_description": "Answers to common questions about EVALL electric vehicles, charging and ownership.",
        "og_type": "website",
        "og_url": "https://www.evall.co.in/resources/faqs",
        "og_image_url": "https://www.evall.co.in/images/og-evall.png",
        "og_image_alt": "EVALL frequently asked questions",
        "twitter_card": "summary_large_image",
        "twitter_title": "EVALL FAQs",
        "twitter_description": "Frequently asked questions about EVALL vehicles and services.",
        "twitter_image_url": "https://www.evall.co.in/images/og-evall.png",
        "schema": ""
      },
      "downloads": {
        "page_id": "downloads",
        "page_path": "/resources/downloads",
        "page_name": "Download Brochures & Manuals",
        "page_title": "Downloads - Brochures, Manuals & Spec Sheets | EVALL",
        "meta_description": "Download EVALL product brochures, technical manuals, user guides and spec sheets for fleet evaluation and service teams.",
        "meta_keywords": "download brochures, EV manuals, spec sheets, product brochure EVALL, technical documents",
        "canonical_url": "https://www.evall.co.in/resources/downloads",
        "robots_meta": "index, follow",
        "og_title": "Downloads - EVALL Brochures & Manuals",
        "og_description": "Brochures, manuals and technical resources available for EVALL vehicles and partners.",
        "og_type": "website",
        "og_url": "https://www.evall.co.in/resources/downloads",
        "og_image_url": "https://www.evall.co.in/images/og-evall.png",
        "og_image_alt": "EVALL downloads and manuals",
        "twitter_card": "summary_large_image",
        "twitter_title": "Downloads - EVALL",
        "twitter_description": "Get product brochures and technical manuals for EVALL vehicles.",
        "twitter_image_url": "https://www.evall.co.in/images/og-evall.png",
        "schema": ""
      },
      "feedback-form": {
        "page_id": "feedback-form",
        "page_path": "/contact/feedback",
        "page_name": "Feedback Form",
        "page_title": "Feedback - EVALL Customer Feedback & Suggestions",
        "meta_description": "Share feedback or suggestions with EVALL. We value customer input to improve vehicle performance, service and product features.",
        "meta_keywords": "EVALL feedback, customer feedback, product suggestions, EV service feedback",
        "canonical_url": "https://www.evall.co.in/contact/feedback",
        "robots_meta": "index, follow",
        "og_title": "Feedback - EVALL",
        "og_description": "Provide feedback or suggestions to EVALL to help us improve our vehicles and services.",
        "og_type": "website",
        "og_url": "https://www.evall.co.in/contact/feedback",
        "og_image_url": "https://www.evall.co.in/images/og-evall.png",
        "og_image_alt": "EVALL feedback form",
        "twitter_card": "summary_large_image",
        "twitter_title": "Feedback - EVALL",
        "twitter_description": "Tell us about your experience with EVALL products and services.",
        "twitter_image_url": "https://www.evall.co.in/images/og-evall.png",
        "schema": ""
      },
      "dealer-locator": {
        "page_id": "dealer-locator",
        "page_path": "/contact/dealer-locator",
        "page_name": "Dealer Locator",
        "page_title": "Dealer Locator - Find EVALL Dealers & Service Centers",
        "meta_description": "Locate authorized EVALL dealers and service centers near you. Search by city to book test drives and service appointments.",
        "meta_keywords": "dealer locator, EVALL dealers, service centers, find dealer, test drive booking",
        "canonical_url": "https://www.evall.co.in/contact/dealer-locator",
        "robots_meta": "index, follow",
        "og_title": "Dealer Locator - EVALL",
        "og_description": "Find authorized EVALL dealers and service centers to schedule test drives and support.",
        "og_type": "website",
        "og_url": "https://www.evall.co.in/contact/dealer-locator",
        "og_image_url": "https://www.evall.co.in/images/og-evall.png",
        "og_image_alt": "EVALL dealer locator",
        "twitter_card": "summary_large_image",
        "twitter_title": "Dealer Locator - EVALL",
        "twitter_description": "Find a dealer or service center near you for EVALL vehicles.",
        "twitter_image_url": "https://www.evall.co.in/images/og-evall.png",
        "schema": ""
      },
      "request-demo": {
        "page_id": "request-demo",
        "page_path": "/contact/request-demo",
        "page_name": "Request a Demo",
        "page_title": "Request a Demo - Book EVALL Test Drive & Fleet Demo",
        "meta_description": "Request a demo or test drive of EVALL vehicles. Schedule fleet demonstrations for operators and decision makers to evaluate EV performance.",
        "meta_keywords": "request demo, book test drive, fleet demo, EV test drive, EVALL demo",
        "canonical_url": "https://www.evall.co.in/contact/request-demo",
        "robots_meta": "index, follow",
        "og_title": "Request a Demo - EVALL",
        "og_description": "Book a test drive or fleet demo to experience EVALL vehicles first hand.",
        "og_type": "website",
        "og_url": "https://www.evall.co.in/contact/request-demo",
        "og_image_url": "https://www.evall.co.in/images/og-evall.png",
        "og_image_alt": "Request a demo for EVALL",
        "twitter_card": "summary_large_image",
        "twitter_title": "Request a Demo - EVALL",
        "twitter_description": "Book a test drive or fleet demonstration for EVALL vehicles.",
        "twitter_image_url": "https://www.evall.co.in/images/og-evall.png",
        "schema": ""
      },
      "customer-support": {
        "page_id": "customer-support",
        "page_path": "/contact/customer-support",
        "page_name": "Customer Support",
        "page_title": "Customer Support - EVALL Helpdesk & Service Assistance",
        "meta_description": "Contact EVALL customer support for service requests, technical help, warranty claims and roadside assistance for electric commercial vehicles.",
        "meta_keywords": "customer support EVALL, helpdesk, warranty claims, roadside assistance, EV technical support",
        "canonical_url": "https://www.evall.co.in/contact/customer-support",
        "robots_meta": "index, follow",
        "og_title": "Customer Support - EVALL",
        "og_description": "Get support for service, warranty and technical assistance from the EVALL helpdesk.",
        "og_type": "website",
        "og_url": "https://www.evall.co.in/contact/customer-support",
        "og_image_url": "https://www.evall.co.in/images/og-evall.png",
        "og_image_alt": "EVALL customer support",
        "twitter_card": "summary_large_image",
        "twitter_title": "Customer Support - EVALL",
        "twitter_description": "Contact EVALL support for service and warranty assistance.",
        "twitter_image_url": "https://www.evall.co.in/images/og-evall.png",
        "schema": ""
      },
      "apply-dealership": {
        "page_id": "apply-dealership",
        "page_path": "/contact/apply-dealership",
        "page_name": "Apply for Dealership",
        "page_title": "Apply for Dealership - Become an EVALL Partner",
        "meta_description": "Apply to become an authorized EVALL dealer or service partner. Learn dealership requirements, benefits and support programs.",
        "meta_keywords": "apply dealership, EVALL dealer application, become dealer, dealership partnership, EV service partner",
        "canonical_url": "https://www.evall.co.in/contact/apply-dealership",
        "robots_meta": "index, follow",
        "og_title": "Apply for Dealership - EVALL",
        "og_description": "Partner with EVALL as an authorized dealer or service partner and grow with the electric mobility market.",
        "og_type": "website",
        "og_url": "https://www.evall.co.in/contact/apply-dealership",
        "og_image_url": "https://www.evall.co.in/images/og-evall.png",
        "og_image_alt": "Apply for EVALL dealership",
        "twitter_card": "summary_large_image",
        "twitter_title": "Apply for Dealership - EVALL",
        "twitter_description": "Become an authorized EVALL dealer or service partner. Apply today.",
        "twitter_image_url": "https://www.evall.co.in/images/og-evall.png",
        "schema": ""
      },
      "privacy-policy": {
        "page_id": "privacy-policy",
        "page_path": "/contact/privacy-policy",
        "page_name": "Privacy Policy",
        "page_title": "Privacy Policy - EVALL",
        "meta_description": "EVALL Privacy Policy: how we collect, use and protect personal data for customers, dealers and site visitors. Read our data practices and rights.",
        "meta_keywords": "privacy policy, data protection, EVALL privacy, cookie policy, personal data, GDPR",
        "canonical_url": "https://www.evall.co.in/contact/privacy-policy",
        "robots_meta": "index, follow",
        "og_title": "EVALL Privacy Policy",
        "og_description": "Read about how EVALL handles personal data, cookies and privacy rights for users and customers.",
        "og_type": "website",
        "og_url": "https://www.evall.co.in/contact/privacy-policy",
        "og_image_url": "https://www.evall.co.in/images/og-evall.png",
        "og_image_alt": "EVALL privacy policy",
        "twitter_card": "summary_large_image",
        "twitter_title": "Privacy Policy - EVALL",
        "twitter_description": "Information on EVALL's privacy practices and how we protect personal data.",
        "twitter_image_url": "https://www.evall.co.in/images/og-evall.png",
        "schema": ""
      },
      "terms-conditions": {
        "page_id": "terms-conditions",
        "page_path": "/contact/terms-and-conditions",
        "page_name": "Terms and Conditions",
        "page_title": "Terms & Conditions - EVALL Website Terms",
        "meta_description": "Terms and conditions governing the use of EVALL website and services. Read the legal terms, usage policies and disclaimers.",
        "meta_keywords": "terms and conditions, website terms, EVALL policies, legal terms, site usage",
        "canonical_url": "https://www.evall.co.in/contact/terms-and-conditions",
        "robots_meta": "index, follow",
        "og_title": "EVALL Terms & Conditions",
        "og_description": "Legal terms, site usage policies and conditions for using EVALL services and website.",
        "og_type": "website",
        "og_url": "https://www.evall.co.in/contact/terms-and-conditions",
        "og_image_url": "https://www.evall.co.in/images/og-evall.png",
        "og_image_alt": "EVALL terms and conditions",
        "twitter_card": "summary_large_image",
        "twitter_title": "Terms & Conditions - EVALL",
        "twitter_description": "Read EVALL's website terms and conditions.",
        "twitter_image_url": "https://www.evall.co.in/images/og-evall.png",
        "schema": ""
      },
      "disclaimers": {
        "page_id": "disclaimers",
        "page_path": "/contact/disclaimers",
        "page_name": "Disclaimers",
        "page_title": "Disclaimers - EVALL",
        "meta_description": "Legal disclaimers for EVALL website, content and third-party links. Read our liability limitations and content accuracy statement.",
        "meta_keywords": "disclaimers, liability, content accuracy, EVALL legal disclaimers",
        "canonical_url": "https://www.evall.co.in/contact/disclaimers",
        "robots_meta": "index, follow",
        "og_title": "EVALL Disclaimers",
        "og_description": "Legal disclaimers and liability information for EVALL website content and services.",
        "og_type": "website",
        "og_url": "https://www.evall.co.in/contact/disclaimers",
        "og_image_url": "https://www.evall.co.in/images/og-evall.png",
        "og_image_alt": "EVALL disclaimers",
        "twitter_card": "summary_large_image",
        "twitter_title": "Disclaimers - EVALL",
        "twitter_description": "Legal disclaimers and content notices for EVALL.",
        "twitter_image_url": "https://www.evall.co.in/images/og-evall.png",
        "schema": ""
      }
    },
  
    advanced_seo: {
      "id": 1,
      "google_site_verification": "google-site-verification=7fKpAqLxJw92hR0sYtQbZmvCeD1uN3PgX5lOaUfWdI8",
      "header_script": `<!-- Google Tag Manager -->
                          <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
                          new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
                          j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
                          'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
                          })(window,document,'script','dataLayer','GTM-TSCSVHM7');</script>
                          <!-- End Google Tag Manager -->`,
      "footer_script": `<!-- Google Tag Manager (noscript) -->
                          <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TSCSVHM7"
                          height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
                          <!-- End Google Tag Manager (noscript) -->`
    }
  };
  